spring:
  application:
    name: VirtualFilesSystem

  datasource:
    url: jdbc:postgresql://file-system-db:5432/file_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://file-system-db:5432/file_system
    user: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org:
      flywaydb: debug


debug: true