version: '3.9'

services:
  file-system-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: file_system
    container_name: file-system-db
    restart: always

  file-system-api:
    build:
      context: ../VirtualFilesSystemApi
      dockerfile: ../docker/Dockerfile
    depends_on:
      - file-system-db
    ports:
      - "8080:8080"
    container_name: file-system-api
    restart: always